# Generated by Django 3.2.5 on 2021-07-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicbankingsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('receiver_name', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=100)),
                ('receiver_email', models.CharField(max_length=100)),
                ('amount_transfer', models.FloatField()),
            ],
        ),
    ]
